# Generated by Django 4.0.3 on 2022-06-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_table',
            name='comments',
        ),
        migrations.AlterField(
            model_name='blog_table',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog_table',
            name='title',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('mob_no', models.TextField(max_length=20)),
                ('comment', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.blog_table')),
            ],
        ),
    ]
