# Generated by Django 4.0.3 on 2022-06-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_blog_table_comments_alter_blog_table_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table',
            name='subscribe',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
