# Generated by Django 4.0.3 on 2022-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_blog_table_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_table',
            name='category',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_table',
            name='pub_draft',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
