# Generated by Django 4.0.3 on 2022-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_blog_table_category_blog_table_pub_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_time',
            field=models.DateTimeField(default='2022-02-02 05:05:05'),
            preserve_default=False,
        ),
    ]
