# Generated by Django 4.0.3 on 2022-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_comments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table',
            name='pub_draft',
            field=models.BooleanField(),
        ),
    ]
