# Generated by Django 4.0.3 on 2022-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_blog_table_pub_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table',
            name='youtube_link',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
