# Generated by Django 4.0.3 on 2022-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_blog_table_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
